spring.application.name=imageliteapi

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/seplag
spring.datasource.username=seplag
spring.datasource.password=seplag123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate / validate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialect (opcional nas versões mais novas do Hibernate)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect